### ISSUE TITLE
Крашится twig в момент переноса файла, не отслеживает корректно файлы

### ISSUE THREAD

**Issue by reznichenko1303** [mrlss/generator-scaffolder#153]
Если заинклюдить файл, в момент, разработки и потом переместить файл допустим в подпапку, и поменять путь подключения, то не обновляет путь и крашится с ошибкой, приходиться перезапускать скафолдер

**Comment by mrlss** [comment]
Fixed in https://github.com/mrlss/generator-scaffolder/commit/884973a96fbdec461a0c83493743e2cc12876b60
