### ISSUE TITLE
Не верный пути при работе на видне и маке в рамках одного таска

### ISSUE THREAD

**Issue by dBulavinov** [mrlss/generator-scaffolder#158]
Привет!
Столкнулись с такой проблемой, если таск был запущен на маке, а потом подключился разраб на винде, то пути, которые генерятся джеесом, для винды имебт не правильный 
вид https://scrstorage.s3.amazonaws.com/1fb5n70h640ytw61500.jpg_1339254_2020-06-09_14-28-34.png

**Comment by mrlss** [comment]
Was fixed in e3e2c4aa3c380e86b3e37d3df8a37599a9ce4701
