### ISSUE TITLE
Console errors and wrong path for images and ajax

### ISSUE THREAD

**Issue by KaterynaZhykharieva** [mrlss/generator-scaffolder#201]
Project type - Markup only, no framework, no engine
Issue appears in developer mode
Windows 10
config: https://s3.amazonaws.com/tz9i2p4ymw/5rm3637876589bm67.jpg
console: https://s3.amazonaws.com/tz9i2p4ymw/q537469lw390951ae8.jpg
sources: https://s3.amazonaws.com/tz9i2p4ymw/53750b30466wla89w3.jpg

**Comment by AlekseyRozhkov** [comment]
Config is changed to match example
```
{
  "styles": {
    ...
    "dest": "assets/css",
  },
  "scripts": {
    ...
    "dest": "assets/js",
  },
...
  "static": {
    "fonts": {
      "src": "fonts",
      "dest": "assets/fonts"
    },
    "images": {
      "src": "images",
      "dest": "assets/images"
    },
    "video": {
      "src": "video",
      "dest": "assets/video"
    },
    "ajax": {
      "src": "inc",
      "dest": "assets/ajax"
    }
  }
}
```
Here generated project structure - https://scrstorage.s3.amazonaws.com/Image_BgLOqJM6T5.jpg
Errors appear because images path was not changed n HTML
`Inc` folder is missing - because it is not used in project, thus - not loaded
