### ISSUE TITLE
Inc folder doesn't exist in Sources tab after running the developer mode

### ISSUE THREAD

**Issue by KaterynaZhykharieva** [mrlss/generator-scaffolder#202]
Project type -markup only, no framework, no engine
Windows 10

Inc folder should have the same path as js, fonts, images and css. Project was just created, there were no changes in config file.
screen shot - https://s3.amazonaws.com/tz9i2p4ymw/r5k4p29614682p352.jpg

**Comment by AlekseyRozhkov** [comment]
It is not shown because was not used in project. Folder itself copy as it should
