### ISSUE TITLE
Fonts and images are missed after changing the path

### ISSUE THREAD

**Issue by KaterynaZhykharieva** [mrlss/generator-scaffolder#204]
Project type - markup only, Bootstrap, no engine. Windows 10

1. We have 4 folders after running the development mode in Sources tab of Development Tools.
2. Change the destination of css, js and fonts to test folder. Save changes, restart development mode.
3. Only scc and js appears at new path. Fonts files are missed. https://s3.amazonaws.com/tz9i2p4ymw/oy6168d02x968w237.jpg
4. Then change the destination of images for the same test folder. Save changes, restart development mode.
5. We still have only css and js at new path. There is no fonts and images. https://s3.amazonaws.com/tz9i2p4ymw/6p1p7um322281m3438.jpg

**Comment by AlekseyRozhkov** [comment]
Generated structure https://scrstorage.s3.amazonaws.com/Image_YYa0H4LDbP.jpg
Same issue with images path in HTML, that should be changed to match config file.
