### ISSUE TITLE
map files

### ISSUE THREAD

**Issue by treepan** [mrlss/generator-scaffolder#30]
https://s3.amazonaws.com/tz9i2p4ymw/xp4g7163t18h7233.jpg pls remove *.map files from dist folder by default

https://s3.amazonaws.com/tz9i2p4ymw/48r761otj3755119.jpg maybe done not minify by default

**Comment by mrlss** [comment]
1. removed by default
2. this build is focus on optimisation of load speed, that's why we consider to left it minify JS/CSS by default.
